version: '3'

services:
  nginx:
    restart: always
    image: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/code/build:/var/www/app:ro
  backend:
    restart: always
    image: marubatsu-backend
    build: ./backend
    expose:
      - "8888"
