version: '3'

services:
  frontend:
    restart: always
    image: marubatsu-frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "127.0.0.1:3000:3000"
    command: yarn start

  backend:
    restart: always
    image: marubatsu-backend
    build: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - PICKLE_PATH=../rl/q-param.pickle
    command: python api.py
