version: 2
jobs:
  build:
    working_directory: ~/marubatsu
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: install packages
          command: pip install --user -r requirements.txt
          working_directory: backend
      - run:
          name: run test
          command: python api_test.py
          working_directory: backend/api
